[book]
authors = ["Alo√Øs Rautureau <alois.rautureau@ens-rennes.fr>", "Paul Adam <paul.adam@ens-rennes.fr"]
language = "en"
multilingual = false
src = "src"
title = "MiniLua"

[output.html]
mathjax-support = true

[build]
build-dir = "docs"
